export const articles = [
  {
    id: "1",
    newspaper: "Long Island Press",
    date: "August 14, 1965",
    description:
      "Screaming teenagers wait for a glimpse of the Beatles at the Hotel Warwick",
  },
  {
    id: "2",
    newspaper: "Daily News",
    date: "February 8, 1964",
    description: "Beatles enthusiasts at Kennedy Airport",
  },
  {
    id: "3",
    newspaper: "The New York Times",
    date: "February 8, 1964",
    description: "Screaming Teenagers Greet the Beatles (Yeah, Yeah)",
  },
  {
    id: "4",
    newspaper: "The New York Times",
    date: "February 8, 1964",
    description:
      "The Beatles Invade, Complete With Long Hair and Screaming Fans",
  },
  {
    id: "5",
    newspaper: "The New York Times",
    date: "February 8, 1964",
    description: "The Beatles",
  },
  {
    id: "6",
    newspaper: "The New York Times",
    date: "February 8, 1964",
    description:
      "The Beatles wave from their suite in the Plaza to their fans outside",
  },
  {
    id: "7",
    newspaper: "The New York Times",
    date: "February 8, 1964",
    description: "It's enough to make you cry",
  },
  {
    id: "8",
    newspaper: "The New York Times",
    date: "February 8, 1964",
    description: "The sincerest form of flattery",
  },
  {
    id: "9",
    newspaper: "The New York Times",
    date: "February 8, 1964",
    description: "Beatles In, Town Knows It",
  },
  {
    id: "10",
    newspaper: "The Christian Science Monitor",
    date: "Unknown",
    description: "Beatles...Ahem...a Secret Weapon",
  },
  {
    id: "11",
    newspaper: "The New York Times",
    date: "February 9, 1964",
    description: "Now...the Beatles are here!",
  },
  {
    id: "12",
    newspaper: "Teen Life",
    date: "1964",
    description: "For you the Beatles are here!",
  },
  {
    id: "13",
    newspaper: "The Christian Science Monitor",
    date: "Unknown",
    description: "You can bank on Beatles",
  },
  {
    id: "14",
    newspaper: "Teen Life",
    date: "1964",
    description: "Guys Just",
  },
  {
    id: "15",
    newspaper: "Unknown",
    date: "February 12, 1964",
    description: "It's Beatles night at Carnegie Hall",
  },
  {
    id: "16",
    newspaper: "NY Journal American",
    date: "February 12, 1964",
    description: "Beatles Buzz Tonight at Carengie Hall",
  },
  {
    id: "17",
    newspaper: "New York Post",
    date: "February 13, 1964",
    description: "Beatles at Carnegie Hall",
  },
  {
    id: "18",
    newspaper: "New York Post",
    date: "February 13, 1964",
    description: "Happy Fan: Happy & Co.",
  },
  {
    id: "19",
    newspaper: "NY Journal American",
    date: "February 11, 1964",
    description: "Beatles Take Wing to Washington",
  },
  {
    id: "20",
    newspaper: "New York Post",
    date: "February 12, 1964",
    description: "The Beatles Storm the Capital",
  },
  {
    id: "21",
    newspaper: "NY Journal American",
    date: "February 11, 1964",
    description: "Why They Go Wild Over the Beatles",
  },
  {
    id: "22",
    newspaper: "NY Journal American",
    date: "February 11, 1964",
    description: "Beatles with Leslie Gould",
  },
  {
    id: "23",
    newspaper: "NY Journal American",
    date: "February 12, 1964",
    description: "If You Must Throw Things...",
  },
  {
    id: "24",
    newspaper: "NY Journal American",
    date: "February 12, 1964",
    description: "Beatles cartoon",
  },
  {
    id: "25",
    newspaper: "New York Post",
    date: "1964",
    description: "Nora Ephron - Harrison",
  },
  {
    id: "26",
    newspaper: "NY Journal American",
    date: "February 11, 1964",
    description: "Somehow the Songs Get Written",
  },
  {
    id: "27",
    newspaper: "NY Journal American",
    date: "February 11, 1964",
    description: "We are the Beatles",
  },
  {
    id: "28",
    newspaper: "New York Post",
    date: "1964",
    description: "Nora Ephron - Starr",
  },
  {
    id: "29",
    newspaper: "New York Times",
    date: "February 14, 1964",
    description: "4,000 Hail Beatles on Arrival in Miami",
  },
  {
    id: "30",
    newspaper: "New York Daily News",
    date: "February 15, 1964",
    description: "Yeh! Yeh! And Yo! Ho!",
  },
  {
    id: "31",
    newspaper: "New York Daily News",
    date: "February 15, 1964",
    description: "Paul on yacht, Southern Trail",
  },
  {
    id: "32",
    newspaper: "London Daily Express",
    date: "1964",
    description: "Cartoon Cavalcade",
  },
  {
    id: "33",
    newspaper: "NY Journal American",
    date: "February 15, 1964",
    description: "Suppose Everybody Went Beatlenuts",
  },
  {
    id: "34",
    newspaper: "Life",
    date: "1964",
    description: "Beatlemania",
  },
  {
    id: "35",
    newspaper: "Life",
    date: "1964",
    description: "Beatlemania",
  },
  {
    id: "36",
    newspaper: "New York Daily News",
    date: "February 7, 1964",
    description: "Beatles Here",
  },
  {
    id: "37",
    newspaper: "The New York Times",
    date: "1964",
    description: "4 Beatles and How They Grew",
  },
];
